common: &common
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

#----------------------------------------------------------------
development:
  <<: *common
  database: db_charmer_sandbox_development
  
  # logs database
  logs:
    <<: *common
    database: db_charmer_logs_development

  # logs database
  slave01:
    <<: *common
    username: db_charmer_ro
    database: db_charmer_sandbox_development

#----------------------------------------------------------------
test:
  <<: *common
  database: db_charmer_sandbox_test

#----------------------------------------------------------------
production:
  <<: *common
  database: db_charmer_sandbox_production
